routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\UserController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\LikeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// ログイン, ユーザー登録
Auth::routes();

// トップページ
Route::get('/', [ItemController::class, 'index'])->name('top');

 // プロフィール詳細
Route::get('users/{user}', [UserController::class, 'show'])->name('users.show');

// プロフィール編集
Route::get('profile/edit', [UserController::class, 'edit'])->name('profile.edit');
Route::patch('profile/edit', [UserController::class, 'update'])->name('profile.update');

// プロフィール画像編集
Route::get('profile/edit_image', [UserController::class, 'editImage'])->name('profile.edit_image');
Route::patch('profile/edit_image', [UserController::class, 'updateImage'])->name('profile.update_image');

// 出品商品一覧
Route::get('users/{user}/exhibitions', [UserController::class, 'itemList'])->name('users.posts');

// 新規出品
// 商品情報編集
// 商品詳細
// 商品削除
Route::resource('items', ItemController::class,  ['except' => ['index']]);

// 商品画像編集
Route::get('items/{item}/edit_image', [ItemController::class, 'editImage'])->name('items.edit_image');
Route::patch('items/{item}/edit_image', [ItemController::class, 'updateImage'])->name('items.update_image');

// 購入確認
Route::post('items/{item}/confirm', [ItemController::class, 'confirm'])->name('items.confirm');
Route::post('items/{item}/finish', [ItemController::class, 'finish'])->name('items.finish');


// 購入確認
Route::post('items/{item}/confirm', [ItemController::class, 'confirm'])->name('items.confirm');
Route::post('items/{item}/finish', [ItemController::class, 'finish'])->name('items.finish');

// お気に入り一覧
// お気に入り登録
// お気に入り削除
Route::resource('likes', LikeController::class,  ['only' => ['index', 'store']]);
Route::delete('likes', [LikeController::class, 'destroy']);

app/Models/Item.php
<?php

namespace App\Models;

use App\Scopes\ItemOrderScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use HasFactory;

    const STATUS_OPEN = 0;
    const STATUS_SOLD = 1;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id',
        'name',
        'description',
        'category_id',
        'price',
        'image',
        'status'
    ];


    /**
     * Relationships
     *
     */

    public function category()
    {
        return $this->belongsTo('App\Models\Category');
    }

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    /**
     * The "booted" method of the model.
     *
     * @return void
     */
    protected static function booted()
    {
        static::addGlobalScope(new ItemOrderScope);
    }
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ImageChangeRequest;
use App\Http\Requests\ItemRequest;
use App\Models\Category;
use App\Models\Item;
use App\Models\Order;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class ItemController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * 商品一覧を表示
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('item.index', [
            'items' => Item::with(['user', 'category'])->get(),
        ]);
    }

    /**
     * 出品画面を表示
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('item.create', [
            'item' => new Item,
            'categories' => Category::all()
        ]);
    }

    /**
     * 出品処理を実行
     *
     * @param  ItemRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ItemRequest $request)
    {
        $path = null;
        $image = $request->file('image', false);
        if ($image !== false) {
            $path = $image->store('items/' . Auth::id(), ['disk' => 'public']);
        }
        $data = $request->only(['name', 'description', 'price', 'category_id']) + [
            'image' => $path,
            'user_id' => Auth::id(),
            'status' => Item::STATUS_OPEN
        ];
        $result = Item::create($data);
        if ($result) {
            return redirect()
                    ->route('users.posts', ['user' => Auth::id()])
                    ->with('success', __('Saved successfully.'));
        } else {
            return back()
                    ->with('error', __('Something went wrong, please try again.'));
        }
    }

    /**
     * 商品詳細を表示
     *
     * @param  Item  $item
     * @return \Illuminate\Http\Response
     */
    public function show(Item $item)
    {
        return view('item.show', [
            'item' => $item
        ]);
    }

    /**
     * 商品の編集画面を表示
     *
     * @param  Item  $item
     * @return \Illuminate\Http\Response
     */
    public function edit(Item $item)
    {
        if ($item->user_id !== Auth::id()) {
            abort(403);
        }
        return view('item.edit', [
            'item' => $item,
            'categories' => Category::all()
        ]);
    }

    /**
     * 商品の編集処理を実行
     *
     * @param  ItemRequest  $request
     * @param  Item  $item
     * @return \Illuminate\Http\Response
     */
    public function update(ItemRequest $request, Item $item)
    {
        if ($item->user_id !== Auth::id()) {
            abort(403);
        }
        $result = $item->update(
            $request->only(['name', 'description', 'price', 'category_id'])
        );
        if ($result) {
            return redirect()
                    ->route('users.posts', ['user' => Auth::id()])
                    ->with('success', __('Saved successfully.'));
        } else {
            return back()
                    ->with('error', __('Something went wrong, please try again.'));
        }
    }

    /**
     * 商品画像の編集画面を表示
     *
     * @param  Item  $item
     * @return \Illuminate\Http\Response
     */
    public function editImage(Item $item)
    {
        if ($item->user_id !== Auth::id()) {
            abort(403);
        }
        return view('item.edit_image', [
            'item' => $item
        ]);
    }

    /**
     * 商品画像の編集処理
     *
     * @param  ImageChangeRequest  $request
     * @param  Item  $item
     * @return \Illuminate\Http\Response
     */
    public function updateImage(ImageChangeRequest $request, Item $item)
    {
        if ($item->user_id !== Auth::id()) {
            abort(403);
        }

        $result = true;
        $message = '';

        $image = $request->file('image', false);
        if ($image !== false && $path = $image->store('items/' . Auth::id(), ['disk' => 'public'])) {
            $oldImage = $item->image;
            $result = $item->update(['image' => $path]);
            if ($result) {
                $message = __('Saved successfully.');
                if (!empty($oldImage)) {
                    Storage::disk('public')->delete($oldImage);
                }
            }
        }
        if ($result) {
            return redirect()
                    ->route('users.posts', ['user' => Auth::id()])
                    ->with('success', $message);
        } else {
            return back()
                    ->with('error', __('Something went wrong, please try again.'));
        }
    }

    /**
     * 商品を削除
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Item $item)
    {
        if ($item->user_id !== Auth::id()) {
            abort(403);
        }
        if($item->delete()) {
            return back()->with('success', __('Deleted successfully.'));
        } else {
            return back()->with('error', __('Something went wrong, please try again.'));
        }

    }

    /**
     * 購入確認画面を表示
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Item  $item
     * @return \Illuminate\Http\Response
     */
    public function confirm(Request $request, Item $item)
    {
        if ($item->status !== Item::STATUS_OPEN) {
            abort(404);
        }
        return view('item.confirm', [
            'item' => $item,
        ]);
    }

    /**
     * 購入処理を行い、完了画面を表示
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Item  $item
     * @return \Illuminate\Http\Response
     */
    public function finish(Request $request, Item $item)
    {
        if ($item->status !== Item::STATUS_OPEN) {
            abort(404);
        }

        // トランザクション
        try {
            DB::transaction(function () use ($item) {

                // 売り切れに変更
                $item->update(['status' => Item::STATUS_SOLD]);

                // 履歴を保存
                $order = Order::create([
                    'user_id' => Auth::id(),
                    'item_id' => $item->id
                ]);
            });

            // 正常時は完了画面へ
            return view('item.finish', [
                'item' => $item,
            ]);

        } catch (\Exception $e) {

            // エラーのため商品詳細へもどる
            return redirect()
                    ->route('items.show', ['item' => $item])
                    ->with('error', __('Ckeck out failed.'));
        }
    }
}

resources/views/item/_form.blade.php
<div class="form-group row">
    <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Item Name') }}</label>
    <div class="col-md-6">
        <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name', $item->name) }}" required autocomplete="name" autofocus>
        @error('name')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
    </div>
</div>

<div class="form-group row">
    <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Item Description') }}</label>

    <div class="col-md-6">
        <textarea rows="5" id="description" class="form-control @error('description') is-invalid @enderror" name="description" required>{{ old('description', $item->description) }}</textarea>

        @error('description')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
    </div>
</div>

<div class="form-group row">
    <label for="price" class="col-md-4 col-form-label text-md-right">{{ __('Price') }}</label>
    <div class="col-md-6">
        <input id="price" type="number" class="form-control @error('price') is-invalid @enderror" name="price" value="{{ old('price', $item->price) }}" required>
        @error('price')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
    </div>
</div>

<div class="form-group row">
    <label for="category_id" class="col-md-4 col-form-label text-md-right">{{ __('Category') }}</label>
    <div class="col-md-6">
        <select id="category_id" class="form-control @error('category_id') is-invalid @enderror" name="category_id" required>
            <option value="">選択してください</option>
            @foreach($categories as $category)
                <option value="{{ $category->id }}"
                    @if($category->id === (int) old('category_id', $item->category_id))
                        selected
                    @endif
                >{{ $category->name }}</option>
            @endforeach
        </select>
        @error('category_id')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
    </div>
</div>

@if (!(isset($item) && $item->id))
<div class="form-group row">
    <label for="profile" class="col-md-4 col-form-label text-md-right">{{ __('Choose Image') }}</label>

    <div class="col-md-6">
        <input type="file" name="image" class="form-control-file @error('image') is-invalid @enderror">
        @error('image')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
    </div>
</div>
@endif

<div class="form-group row mb-0">
    <div class="col-md-8 offset-md-4">
        <button type="submit" class="btn btn-primary">
            {{ __('Post') }}
        </button>
    </div>
</div>

resources/views/item/confirm.blade.php
@extends('layouts.app')

@section('title', __('Confirm Check Out'))

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <h1>@yield('title')</h1>
            @include('shared.item_detail')
            <form method="POST" action="{{ route('items.finish', ['item' => $item->id]) }}">
                @csrf
                <button class="btn btn-block btn-primary">{{ __('I Confirmed, Proceed to Check Out') }}</button>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/item/create.blade.php
@extends('layouts.app')

@section('title', __('Post Item'))

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card">
                <h1 class="card-header">@yield('title')</h1>

                <div class="card-body">
                    <form method="POST" action="{{ route('items.store') }}" enctype="multipart/form-data">
                        @csrf
                        @include('item._form')
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/item/edit.blade.php
@extends('layouts.app')

@section('title', __('Edit Item'))

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card">
                <h1 class="card-header">@yield('title')</h1>

                <div class="card-body">
                    <form method="POST" action="{{ route('items.update', ['item' => $item]) }}">
                        @csrf
                        @method('patch')
                        @include('item._form')
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/item/edit_image.blade.php
@extends('layouts.app')

@section('title', __('Edit Item Image'))

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card">
                <h1 class="card-header">@yield('title')</h1>

                <div class="card-body">
                    <form method="POST" action="{{ route('items.update_image', ['item' => $item->id]) }}" enctype="multipart/form-data">
                        @csrf
                        @method('PATCH')
                        @include('shared.edit_image', ['image' => $item->image])
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/item/finish.blade.php
@extends('layouts.app')

@section('title', __('Thank you for your purchase'))

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <h1>@yield('title')</h1>
            @include('shared.item_detail')

            <a href="{{ route('top') }}">{{ __('Back to Top') }}</a>
        </div>
    </div>
</div>
@endsection

resources/views/item/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h1>{{ env('APP_LEAD_TEXT', __('Free Market')) }}</h1>
    @if (count($items) === 0)
    <p class="alert alert-warning px-3" role="alert">{{ __('There are no items.') }}</p>
    @else
    @include('shared.item_list', ['control' => false])
    @endif
</div>
@endsection

resources/views/item/show.blade.php
<?php
use App\Models\Item;
use Illuminate\Support\Facades\Auth;
?>
@extends('layouts.app')

@section('title', __('Item Detail'))

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <h1>@yield('title')</h1>
            @include('shared.item_detail')
            @if ($item->user_id === Auth::id())
                <a class="btn btn-block btn-outline-primary" href="{{ route('items.edit', ['item' => $item]) }}">
                    <i aria-hidden="true" class="fas fa-edit"></i>
                    {{ __('Edit') }}
                </a>
            @elseif($item->status === Item::STATUS_OPEN)
            <form method="POST" action="{{ route('items.confirm', ['item' => $item]) }}">
                @csrf
                <button class="btn btn-block btn-primary">{{ __('Check Out') }}</button>
            </form>
            @else
                <button class="btn btn-secondary btn-block" disabled>{{ __('Sold Out') }}</button>
            @endif
        </div>
    </div>
</div>
@endsection