routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\UserController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\LikeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// ログイン, ユーザー登録
Auth::routes();

// トップページ
Route::get('/', [ItemController::class, 'index'])->name('top');

 // プロフィール詳細
Route::get('users/{user}', [UserController::class, 'show'])->name('users.show');

// プロフィール編集
Route::get('profile/edit', [UserController::class, 'edit'])->name('profile.edit');
Route::patch('profile/edit', [UserController::class, 'update'])->name('profile.update');

// プロフィール画像編集
Route::get('profile/edit_image', [UserController::class, 'editImage'])->name('profile.edit_image');
Route::patch('profile/edit_image', [UserController::class, 'updateImage'])->name('profile.update_image');

// 出品商品一覧
Route::get('users/{user}/exhibitions', [UserController::class, 'itemList'])->name('users.posts');

// 新規出品
// 商品情報編集
// 商品詳細
// 商品削除
Route::resource('items', ItemController::class,  ['except' => ['index']]);

// 商品画像編集
Route::get('items/{item}/edit_image', [ItemController::class, 'editImage'])->name('items.edit_image');
Route::patch('items/{item}/edit_image', [ItemController::class, 'updateImage'])->name('items.update_image');

// 購入確認
Route::post('items/{item}/confirm', [ItemController::class, 'confirm'])->name('items.confirm');
Route::post('items/{item}/finish', [ItemController::class, 'finish'])->name('items.finish');


// 購入確認
Route::post('items/{item}/confirm', [ItemController::class, 'confirm'])->name('items.confirm');
Route::post('items/{item}/finish', [ItemController::class, 'finish'])->name('items.finish');

// お気に入り一覧
// お気に入り登録
// お気に入り削除
Route::resource('likes', LikeController::class,  ['only' => ['index', 'store']]);
Route::delete('likes', [LikeController::class, 'destroy']);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'profile',
        'image'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Relationships
     *
     */
    public function items()
    {
        return $this->hasMany('App\Models\Item');
    }

    public function likedItems()
    {
        return $this->belongsToMany('App\Models\Item', 'likes');
    }

    public function orders()
    {
        return $this->hasMany('App\Models\Order');
    }

    /**
     * カスタムメソッド
     *
     */
    public function isItemLiked(int $item_id)
    {
        return $this->likedItems->where('id', $item_id)->count() > 0;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use App\Http\Requests\ImageChangeRequest;
use App\Http\Requests\ProfileRequest;
use App\Models\User;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * プロフィールを表示
     *
     * @param  User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('user.show', [
            'user' => $user,
        ]);
    }

    /**
     * 出品中商品の一覧を表示
     *
     * @param User $user
     * @return \Illuminate\Http\Response
     */
    public function itemList(User $user)
    {
        return view('user.item_list', [
            'user' => $user
        ]);
    }

    /**
     * プロフィール編集画面を表示
     *
     * @return \Illuminate\Http\Response
     */
    public function edit()
    {
        return view('user.edit', [
            'user' => Auth::user(),
        ]);
    }

    /**
     * プロフィール編集処理を実行
     *
     * @param  ProfileRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function update(ProfileRequest $request)
    {
        $user = Auth::user();
        if ($user->update($request->all())) {
            return redirect()
                    ->route('users.show', ['user' => $user])
                    ->with('success', __('Saved successfully.'));
        } else {
            return back()
                    ->with('error', __('Something went wrong, please try again.'));
        }
    }

    /**
     * 画像編集フォームを表示
     *
     * @return void
     */
    public function editImage()
    {
        return view('user.edit_image', [
            'user' => Auth::user(),
        ]);
    }

    /**
     * プロフィール画像編集処理を実行
     *
     * @param  ImageChangeRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function updateImage(ImageChangeRequest $request)
    {
        $result = true;
        $message = '';

        $user = Auth::user();
        $image = $request->file('image', false);
        if ($image !== false && $path = $image->store('users/' . $user->id, ['disk' => 'public'])) {
            $oldImage = $user->image;
            $result = $user->update(['image' => $path]);
            if ($result) {
                $message = __('Saved successfully.');
                if (!empty($oldImage)) {
                    Storage::disk('public')->delete($oldImage);
                }
            }
        }
        if ($result) {
            return redirect()
                    ->route('users.show', ['user' => $user])
                    ->with('success', $message);
        } else {
            return back()
                    ->with('error', __('Something went wrong, please try again.'));
        }
    }
}

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('title', __('Edit Profile'))

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card">
                <h1 class="card-header">@yield('title')</h1>

                <div class="card-body">
                    <form method="POST" action="{{ route('profile.update') }}">
                        @csrf
                        @method('PATCH')
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>
                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name', $user->name) }}" required autocomplete="name" autofocus>
                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="profile" class="col-md-4 col-form-label text-md-right">{{ __('Profile') }}</label>

                            <div class="col-md-6">
                                <textarea rows="5" id="profile" class="form-control @error('profile') is-invalid @enderror" name="profile">{{ old('profile', $user->profile) }}</textarea>

                                @error('profile')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Update') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/edit_image.blade.php
@extends('layouts.app')

@section('title', __('Edit Profile Image'))

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card">
                <h1 class="card-header">@yield('title')</h1>

                <div class="card-body">
                    <form method="POST" action="{{ route('profile.update_image') }}" enctype="multipart/form-data">
                        @csrf
                        @method('PATCH')
                        @include('shared.edit_image', ['image' => $user->image])
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/item_list.blade.php
@extends('layouts.app')

@section('title', __(':name\'s Item List', ['name' => $user->name]))

@section('content')
<div class="container">
        <h1>@yield('title')</h1>
        <div class="text-right mb-3">
            <a class="btn btn-success" href="{{ route('items.create') }}">{{ __('New Item') }}</a>
        </div>
        @include('shared.item_list', ['items' => $user->items()->get(), 'control' => true])
    </div>
</div>
@endsection

resources/views/user/show.blade.php
@extends('layouts.app')

@section('title', __('Profile'))

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8 mt-3">
            <div class="card">
                <h1 class="card-header">@yield('title')</h1>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            @if ($user->image)
                                <img src="{{ asset('storage/' . $user->image) }}" class="img-fluid rounded">
                            @else
                                <img src="{{ asset('img/noimage.png') }}" class="img-fluid rounded">
                            @endif
                            @if ($user->id === Auth::id())
                                <a href="{{ route('profile.edit_image') }}">
                                    <i class="fas fa-image"></i>
                                    {{ __('Change this image.') }}
                                </a>
                            @endif
                        </div>
                        <div class="col-md-6">
                            <p class="lead">{{ $user->name }}</p>
                            <p>{{ $user->profile }}</p>
                            <p>{{ __('Posted Items') }}: {!! number_format($user->items->count()) !!}</p>
                            @if ($user->id === Auth::id())
                                <a class="" href="{{ route('profile.edit') }}">
                                    <i class="fas fa-user-edit"></i>
                                    {{ __('Edit Profile') }}
                                </a>
                            @endif
                        </div>
                    </div>
                    @if ($user->id === Auth::id())
                    <h2 class="mt-5">{{ __('Orders') }}</h2>
                    <ul class="list-group">
                        @forelse ($user->orders as $order)
                            <li class="list-group-item">
                                <small class="pr-2">{{ $order->item->created_at->format('Y.m.d H:i') }}</small>
                                <a class="font-weight-bold" href="{{ route('items.show', ['item' => $order->item]) }}">
                                    {{ $order->item->name }}
                                </a>
                                :
                                {{ number_format($order->item->price) }}円
                                <small class="pl-2">
                                    出品者
                                    <a href="{{ route('users.show', ['user' => $order->item->user_id]) }}">
                                    {{ $order->item->user->name }}さん
                                    </a>
                                </small>
                            </li>
                        @empty
                            <li class="list-group-item">履歴はありません。</li>
                        @endforelse
                    </ul>
                    @endif
                </div>
            </div>
        </div>
    </div>

</div>
@endsection