routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\UserController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\LikeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// ログイン, ユーザー登録
Auth::routes();

// トップページ
Route::get('/', [ItemController::class, 'index'])->name('top');

 // プロフィール詳細
Route::get('users/{user}', [UserController::class, 'show'])->name('users.show');

// プロフィール編集
Route::get('profile/edit', [UserController::class, 'edit'])->name('profile.edit');
Route::patch('profile/edit', [UserController::class, 'update'])->name('profile.update');

// プロフィール画像編集
Route::get('profile/edit_image', [UserController::class, 'editImage'])->name('profile.edit_image');
Route::patch('profile/edit_image', [UserController::class, 'updateImage'])->name('profile.update_image');

// 出品商品一覧
Route::get('users/{user}/exhibitions', [UserController::class, 'itemList'])->name('users.posts');

// 新規出品
// 商品情報編集
// 商品詳細
// 商品削除
Route::resource('items', ItemController::class,  ['except' => ['index']]);

// 商品画像編集
Route::get('items/{item}/edit_image', [ItemController::class, 'editImage'])->name('items.edit_image');
Route::patch('items/{item}/edit_image', [ItemController::class, 'updateImage'])->name('items.update_image');

// 購入確認
Route::post('items/{item}/confirm', [ItemController::class, 'confirm'])->name('items.confirm');
Route::post('items/{item}/finish', [ItemController::class, 'finish'])->name('items.finish');


// 購入確認
Route::post('items/{item}/confirm', [ItemController::class, 'confirm'])->name('items.confirm');
Route::post('items/{item}/finish', [ItemController::class, 'finish'])->name('items.finish');

// お気に入り一覧
// お気に入り登録
// お気に入り削除
Route::resource('likes', LikeController::class,  ['only' => ['index', 'store']]);
Route::delete('likes', [LikeController::class, 'destroy']);

resources/views/shared/edit_image.blade.php
<div class="form-group row">
    <label class="col-md-4 col-form-label text-md-right">{{ __('Current Image') }}</label>
    <div class="col-md-6">
        @if ($image)
            <img src="{{ asset('storage/' . $image) }}" class="img-fluid rounded">
        @else
            <img src="{{ asset('img/noimage.png') }}" class="img-fluid rounded">
        @endif
    </div>
</div>

<div class="form-group row">
    <label for="profile" class="col-md-4 col-form-label text-md-right">{{ __('Choose Image') }}</label>

    <div class="col-md-6">
        <input type="file" name="image" class="form-control-file @error('image') is-invalid @enderror">
        @error ('image')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
        @enderror
    </div>
</div>

<div class="form-group row mb-0">
    <div class="col-md-8 offset-md-4">
        <button type="submit" class="btn btn-primary">
            {{ __('Update') }}
        </button>
    </div>
</div>

resources/views/shared/flash_message.blade.php
<div class="container">
    @if ($message = Session::get('success'))
    <div class="alert alert-success alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
    @endif

    @if ($message = Session::get('error'))
    <div class="alert alert-danger alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
    @endif

    @if ($message = Session::get('warning'))
    <div class="alert alert-warning alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
    @endif

    @if ($message = Session::get('info'))
    <div class="alert alert-info alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
    @endif
</div>

resources/views/shared/item_detail.blade.php
<dl class="row my-4">
    <dt class="col-md-4 text-md-right">{{ __('Item Name') }}</dt>
    <dd class="col-md-8">{{ $item->name }}</dd>
    <dt class="col-md-4 text-md-right">{{ __('Image') }}</dt>
    <dd class="col-md-8"><img src="{{ asset('storage/' . $item->image) }}" class="img-fluid rounded"></dd>
    <dt class="col-md-4 text-md-right">{{ __('Category') }}</dt>
    <dd class="col-md-8">{{ $item->category->name }}</dd>
    <dt class="col-md-4 text-md-right">{{ __('Price') }}</dt>
    <dd class="col-md-8">{{ number_format($item->price) }}円</dd>
    <dt class="col-md-4 text-md-right">{{ __('Item Description') }}</dt>
    <dd class="col-md-8">{{ $item->description }}</dd>
</dl>

resources/views/shared/item_list.blade.php
<?php
use App\Models\Item;
?>
@if (count($items) === 0)
<p class="alert alert-warning px-3" role="alert">{{ __('There are no items.') }}</p>
@else
<ul class="row list-unstyled">
    @foreach ($items as $key => $item)
    <li class="col-md-6 col-lg-4 py-3">
        <div class="card">
            <div class="card-header">
                @if($item->status === Item::STATUS_OPEN)
                    <span class="badge badge-success float-right mt-1">出品中</span>
                @else
                    <span class="badge badge-warning float-right mt-1">売り切れ</span>
                @endif
                {{ $item->name }}
            </div>
            <div class="card-body">
                <a href="{{ route('items.show', ['item' => $item->id]) }}">
                    <img src="{{ asset('storage/' . $item->image) }}" class="img-fluid rounded">
                </a>
                <div class="row mt-2">
                    <div class="col">
                        @if (!$control)
                        <form class="d-inline-block" method="POST" action="{{ route('likes.store') }}">
                            @csrf
                            <input type="hidden" name="item_id" value="{{ $item->id }}">
                            <a href="javascript:void(0)" onClick="this.parentElement.submit();">
                            @if(Auth::user()->isItemLiked($item->id))
                                @method('delete')
                                <i class="fas fa-lg fa-star text-danger"></i>
                            @else
                                <i class="far fa-lg fa-star text-danger"></i>
                            @endif
                            </a>
                        </form>
                        @endif
                        <span class="font-weight-bold">{{ number_format($item->price) }}円</span>
                    </div>
                    <div class="col-auto text-right">
                        <small>
                            @if($control)
                                {{ $item->updated_at }}
                            @else
                                {{ $item->created_at->format('Y.m.d') }}
                            @endif
                        </small>
                    </div>
                </div>
                <p class="my-1 small">カテゴリ: {{ $item->category->name }}</p>
                @if (!$control)
                <p class="my-1 small">
                    出品者:
                    <a href="{{ route('users.show', ['user' => $item->user_id]) }}">
                        {{ $item->user->name }}さん
                    </a>
                </p>
                @endif
                <p class="mb-0">{{ $item->description }}</p>
                @if ($control)
                <ul class="row list-unstyled mt-1">
                    <li class="col-auto pt-1">
                        <a href="{{ route('items.edit', ['item' => $item->id]) }}" class=""><i class="fas fa-edit"></i>
                            {{ __('Edit') }}</a>
                    </li>
                    <li class="col-auto pt-1">
                        <a href="{{ route('items.edit_image', ['item' => $item->id]) }}" class=""><i class="fas fa-image"></i>
                            {{ __('Edit Image') }}</a>
                    </li>
                    <li class="col text-right">
                        <form method="POST" action="{{ route('items.destroy', ['item' => $item->id]) }}">
                            @csrf
                            @method('delete')
                            <button class="btn btn-sm btn-danger">
                                <i class="fas fa-trash-alt"></i>
                                {{ __('Delete') }}
                            </button>
                        </form>
                    </li>
                </ul>
                @endif
            </div>
        </div>
    </li>
    @endforeach
</ul>
@endif